# Generated by Django 2.1.3 on 2018-12-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='имя')),
                ('surname', models.CharField(max_length=25, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=25, verbose_name='отчество')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('adress', models.CharField(max_length=2000, verbose_name='адрес')),
                ('index', models.FloatField(verbose_name='индекс')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Ordered_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_prise', models.FloatField(verbose_name='оплаченная стоимость')),
                ('order_amount', models.FloatField(verbose_name='заказанное количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.Order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.CharField(max_length=400, verbose_name='описание')),
                ('prise', models.FloatField(verbose_name='стоимость')),
                ('amount', models.FloatField(verbose_name='количество')),
                ('product_type', models.CharField(choices=[('plant', 'растение'), ('liquid', 'жидкость'), ('item', 'предмет')], max_length=8, verbose_name='тип товара')),
                ('img_src_min', models.CharField(max_length=25, verbose_name='изображение мини')),
                ('img_src_full', models.CharField(max_length=25, verbose_name='изображение полное')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AddField(
            model_name='ordered_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.Product', verbose_name='товар'),
        ),
    ]
