# Generated by Django 2.1.3 on 2018-12-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_src_full',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_src_min',
        ),
        migrations.AddField(
            model_name='product',
            name='imgsrc_full',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='полное изобранжение'),
        ),
        migrations.AddField(
            model_name='product',
            name='imgsrc_min',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='мини изобранжение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='email'),
        ),
    ]
