# Generated by Django 2.1.3 on 2018-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20181211_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgsrc_full',
            field=models.ImageField(blank=True, default='', upload_to='img/', verbose_name='полное изобранжение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgsrc_min',
            field=models.ImageField(blank=True, default='', upload_to='img/', verbose_name='мини изобранжение'),
        ),
    ]
