# Generated by Django 2.1.3 on 2018-12-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_auto_20181211_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgsrc_full',
            field=models.ImageField(blank=True, default='img.svg', upload_to='img/', verbose_name='полное изобранжение'),
        ),
    ]
