# Generated by Django 2.1.3 on 2018-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_auto_20181211_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgsrc_full',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='полное изобранжение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgsrc_min',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='мини изобранжение'),
        ),
    ]
