# Generated by Django 2.1.3 on 2018-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_auto_20181212_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='index',
            field=models.IntegerField(verbose_name='индекс'),
        ),
        migrations.AlterField(
            model_name='ordered_product',
            name='order_amount',
            field=models.IntegerField(verbose_name='заказанное количество'),
        ),
        migrations.AlterField(
            model_name='ordered_product',
            name='order_prise',
            field=models.IntegerField(verbose_name='оплаченная стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise',
            field=models.IntegerField(verbose_name='стоимость'),
        ),
    ]
